# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = ["github.com/ethereum/go-ethereum"]
ignored = ["github.com/ethereum/go-ethereum/*"]

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  source = "github.com/ya-enot/cosmos-sdk"
  branch = "develop"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  source = "github.com/Etherus-org/tendermint"
  branch = "dukei-develop"
 
[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  source = "github.com/Etherus-org/go-ethereum.git"
  branch = "dukei-develop-f1.8.6"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.x"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "0.x"

# From tendermint
[[override]]
  name = "golang.org/x/net"
  revision = "292b43bbf7cb8d35ddf40f8d5100ef3837cced3f"

[[override]]
  name = "github.com/tendermint/iavl"
  source = "github.com/ya-enot/iavl"
  branch = "ya-enot-v0.9.2"

[[override]]
  name = "github.com/tendermint/go-amino"
  source = "github.com/ya-enot/go-amino"
  version = "=0.10.1"

[prune]
  go-tests = true
  unused-packages = true

  #https://github.com/golang/dep/issues/1223
  [[prune.project]]
    name = "github.com/karalabe/hid"
    unused-packages = false
  
  [[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    unused-packages = false
    go-tests = false

